# NumPy

##### NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

### Import NumPy library as name np

In [1]:
import numpy as np

#### Let's take an list and convert it into the numpy array

In [2]:
l = [1,2,3]

In [3]:
np.array(l)

array([1, 2, 3])

##### Simply by the array()

#### Now the time for 2 Dimensional Array
##### From a 2D list

In [4]:
m = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(m)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### The arange method creates a NumPy array between the given range

In [6]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

#### Here 2 is the step size

In [7]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

#### ones() function creates a NumPy array of 1
Here the arugument can be a single integer or an touple
##### for an integer it produces a 1D array of all elements 1

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

##### For a touple it produces a 2D array of all the elements 1

In [9]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### here we can use reshape() for build a 2D array from 1D array

In [10]:
np.ones(9).reshape(3,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Ex :

In [11]:
np.arange(1.5,4,0.5)

array([1.5, 2. , 2.5, 3. , 3.5])

##### In the above case of arange() we can create a array with start and end and with the step size ...<br> But linespace() is used to create the array  with the same difference between all the elements

In [12]:
np.linspace(10,20,3)

array([10., 15., 20.])

In [13]:
np.linspace(0,5,5)

array([0.  , 1.25, 2.5 , 3.75, 5.  ])

#### eye() is used for create an identity matrix

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### random
#### rand( ) is used to create an array of random number 

In [15]:
np.random.rand(5)

array([0.50040054, 0.59252999, 0.62956605, 0.20655461, 0.46329785])

#### We can pass 2 arguments for create a 2D array

In [16]:
np.random.rand(5,5)

array([[0.10764576, 0.99635123, 0.79145134, 0.60641115, 0.63175352],
       [0.83229006, 0.21710515, 0.20381897, 0.08808302, 0.76590348],
       [0.52624607, 0.1564813 , 0.60053851, 0.26419286, 0.97654643],
       [0.46329455, 0.73321412, 0.81630794, 0.41970033, 0.32864635],
       [0.90256307, 0.5461318 , 0.24649463, 0.46757992, 0.32825284]])

#### randn( ) is used to create an array of random numbers sampled from a standard distribution

In [17]:
np.random.randn(4)

array([-1.38711858,  1.00384089,  1.31316803, -1.88544119])

#### Here also we can pass 2 arguments 

In [18]:
np.random.randn(4,4)

array([[-0.59786967,  0.26614755, -1.0958819 , -0.18332479],
       [-0.64324692, -0.36436198,  1.55003863, -1.35743129],
       [ 0.53013105, -0.40887143, -1.23888229,  0.02176395],
       [ 0.95859338,  1.39886377,  0.20998443, -0.31106323]])

#### randint( ) is used to create an array of random integers<br>randint(low, high, size, dtype='l')

In [19]:
np.random.randint(1,100,10)

array([77, 32,  3, 50, 31, 32, 32,  9, 41, 94])

#### Here we first create the array and then reshape it to a 2D array

In [20]:
arr = np.random.randint(1,100,9).reshape(3,3) 

In [21]:
arr

array([[24, 24, 76],
       [17, 70, 28],
       [16, 15, 85]])

#### max( ) is used to get the maximum value form an array

In [22]:
arr.max()

85

#### Also for minimum use min( )

In [23]:
arr.min()

15

#### For mean of all the element of the array

In [24]:
arr.mean()

39.44444444444444

#### argmax() is for the index at which the maximum value is present

In [25]:
arr.argmax()

8

In [26]:
arr.all()

True

In [27]:
arr.astype(dtype = "int")

array([[24, 24, 76],
       [17, 70, 28],
       [16, 15, 85]])

#### For data type

In [28]:
arr.dtype

dtype('int32')

#### For diagonal of an array

In [29]:
arr.diagonal()

array([24, 70, 85])

In [30]:
arr.any()

True

#### For use of random only we can import as below

In [31]:
from numpy.random import randint

In [32]:
randint(2,10,9)

array([7, 9, 9, 9, 9, 5, 9, 4, 3])