# NumPy Indexing And Selection

#### Let's create an array of integers from 1 to 10 

In [3]:
import numpy as np

In [4]:
arr =np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### We can get the value by the index number

In [6]:
arr[8]

8

#### The elements  from index 2 to 3 (excluded)

In [7]:
arr[2:3]

array([2])

#### Same thing for 2 to 5

In [8]:
arr[2:5]

array([2, 3, 4])

#### Geting all the elements before index 5(excluded) 

In [85]:
arr[:5] #arr[0:5]

array([0, 1, 2, 3, 4])

#### negetave index means from opposite site (means from end)

In [90]:
arr[-1]

10

#### All the elements from index 5

In [92]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

#### We can change the value of a specific sub array or of a specific element 

In [94]:
arr[0:5] = 100

In [95]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [96]:
arr = np.arange(0,11)

#### If we change the value of the element after slicing the array then the value in the array also changed 

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
slice_of_arr =  arr[0:6]

In [12]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [13]:
slice_of_arr[:] = 100

In [14]:
slice_of_arr

array([100, 100, 100, 100, 100, 100])

In [15]:
arr #invariability

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

#### But If we change the value of the element after copying from the array then the value in the array will not changed 

In [107]:
arr = np.arange(0,11)

In [108]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
arr_copy = arr.copy()

In [110]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
arr_copy[:] = 100

In [112]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [113]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### As seen above the value was not canged 

# 2D Array
#### The same thing we can do in row and column for an 2D array

In [118]:
arr = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [119]:
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [120]:
arr[0][2]

15

In [121]:
arr[2][2]

45

In [122]:
arr[0]

array([ 5, 10, 15])

In [126]:
arr[:,1:2]

array([[10],
       [25],
       [40]])

In [127]:
arr[:,:-2]

array([[ 5],
       [20],
       [35]])

In [128]:
arr[1,2]

30

In [130]:
arr[-1,1]

40

In [132]:
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [133]:
arr[:2,1:]

array([[10, 15],
       [25, 30]])

In [134]:
arr[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [139]:
arr[:,:2]

array([[ 5, 10],
       [20, 25],
       [35, 40]])

In [140]:
arr[1:2,:]

array([[20, 25, 30]])

### Some interesting stuffs.....

In [141]:
arr = np.arange(1,11)

In [142]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [144]:
bool_arr  = arr > 5

In [145]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [146]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [147]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [148]:
arr[arr<3]

array([1, 2])

In [149]:
arr[arr%2==0]

array([ 2,  4,  6,  8, 10])

In [150]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Assignment

In [151]:
arr = np.arange(50).reshape(5,10)

In [152]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

#### You have to extract the sub array [21, 22, 23, 24] and [13,14,15] from the arr

In [153]:
#Do it here

### Ans:

In [154]:
arr[2:3,1:5]

array([[21, 22, 23, 24]])

In [155]:
arr[1:2,3:6]

array([[13, 14, 15]])